apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-mockup-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redditmockup
  template:
    metadata:
      labels:
        app: redditmockup
    spec:
      containers:
        - name: redditmockup
          image: reddit-mockup-web:latest
    